In [135]:
import pandas as pd
import numpy as np

In [136]:
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [137]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [138]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [139]:
df['Age'].isnull().sum()

np.int64(0)

In [140]:
df.drop(columns=['Cabin'], inplace=True)

In [141]:
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])

In [142]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [143]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [144]:
df.drop_duplicates(inplace=True)

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

Converting sex to numerical value
male - 0
female - 1

In [146]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [147]:
df['Sex']=df['Sex'].map({'male':0,'female':1})

In [148]:
df['Sex'].dtype

dtype('int64')

In [149]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,S

In [150]:
df['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [151]:
df = pd.get_dummies(df, columns=['Embarked'])

In [152]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,False,False,True
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,False,False,True

In [153]:
df.rename(columns={
    'PassengerId': 'passenger_id',
    'Survived': 'survived',
    'Pclass': 'passenger_class',
    'Name': 'name',
    'Sex': 'sex',
    'Age': 'age',
    'SibSp': 'siblings_spouse',
    'Parch': 'parents_children',
    'Fare': 'fare',
}, inplace=True)

In [154]:
print(df.info())
print(df.head())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   passenger_id      891 non-null    int64
 1   survived          891 non-null    int64
 2   passenger_class   891 non-null    int64
 3   name              891 non-null    object
 4   sex               891 non-null    int64
 5   age               891 non-null    float64
 6   siblings_spouse   891 non-null    int64
 7   parents_children  891 non-null    int64
 8   Ticket            891 non-null    object
 9   fare              891 non-null    float64
 10  Embarked_C        891 non-null    bool
 11  Embarked_Q        891 non-null    bool
 12  Embarked_S        891 non-null    bool
dtypes: bool(3), float64(2), int64(6), object(2)
memory usage: 72.3+ KB
None
   passenger_id  survived  passenger_class  \
0             1         0                3
1             2         1                1
2             3         1                3
3             4         1                1
4             5         0                3

                                                name  sex   age  \
0                            Braund, Mr. Owen Harris    0  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0
2                             Heikkinen, Miss. Laina    1  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0
4                           Allen, Mr. William Henry    0  35.0

   siblings_spouse  parents_children            Ticket     fare  Embarked_C  \
0                1                 0         A/5 21171   7.2500       False
1                1                 0          PC 17599  71.2833        True
2                0                 0  STON/O2. 3101282   7.9250       False
3                1                 0            113803  53.1000       False
4                0                 0            373450   8.0500       False

   Embarked_Q  Embarked_S
0       False        True
1       False       False
2       False        True
3       False        True
4       False        True
passenger_id        0
survived            0
passenger_class     0
name                0
sex                 0
age                 0
siblings_spouse     0
parents_children    0
Ticket              0
fare                0
Embarked_C          0
Embarked_Q          0
Embarked_S          0
dtype: int64

In [155]:
df.to_csv("clean_titanic.csv", index=False)